### PR TITLE
[WIP] Fix padding on mobile devices, use full width and let the content flow

### PR DESCRIPTION
**Pull request by sandrokeil**
**Not ready for merge**

- Removed some clearfixes for better content flow
- Fixed heading size for mobile (We should use EM, pixels are a pain for font size, so far I know)
- horizontal scrollbar is gone
- Fixed wrong HTML

### CODE REVIEW

**Comment by sandrokeil** [comment]
We need one more guy for the hall of fame. I don't know why the first row is not fullfilled. I have some floating issues on iPad with Chrome/Safari in Landscape mode, but Chrome says it is ok. I guess that's a one pixel issue of the break points.

**Review by prolic — APPROVED** [review]

**Comment by sandrokeil** [comment]
iPhone 5s box glitches on current website

file_000 1

**Comment by sandrokeil** [comment]
iPad Air 2 issues with this fix, but Google Chrome Emulator shows no issues. It's a pity.

file_001

file_000

**Comment by codeliner** [comment]
thx, we recognized similar issues on iPad and iPhone today. I'll incorporate your fixes and come up with a solution tomorrow. :+1:

**Comment by prolic** [comment]
@sandrokeil this seemed to be forgotten, currently it's a conflict there, do you want to resolve it or we just close it?

/cc @codeliner

**Comment by sandrokeil** [comment]
@codeliner What do you think?

**Comment by prolic** [comment]
Closed because of inactivity. Feel free to reopen.

**Pull request closed without merging**
